# Generated by Django 4.1.3 on 2023-04-06 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='propiedades/images')),
                ('descripcion', models.TextField()),
                ('habitaciones', models.IntegerField()),
                ('bano', models.IntegerField()),
                ('estacionamiento', models.IntegerField()),
                ('creado', models.DateField(default=datetime.date.today)),
                ('vendedorId', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
