# Generated by Django 4.1.3 on 2023-04-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table=None,
        ),
    ]
