# Generated by Django 4.1.3 on 2023-04-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0002_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='usuarios',
        ),
    ]
