# Generated by Django 4.1.3 on 2023-04-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0003_alter_admin_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
