# Generated by Django 4.1.3 on 2023-04-25 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_inmobiliaria', '0005_alter_propiedad_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='vendedorId',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
