# Generated by Django 4.1.3 on 2023-04-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_inmobiliaria', '0006_remove_propiedad_vendedorid_propiedad_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(default='Sin teléfono', max_length=20),
        ),
    ]
