# Generated by Django 4.1.3 on 2023-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0007_remove_vendedor_apellido_remove_vendedor_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='user',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=255),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(default='Sin teléfono', max_length=10),
        ),
    ]
