# Generated by Django 4.1.3 on 2023-04-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0008_remove_vendedor_user_vendedor_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_inmobiliaria.vendedor'),
        ),
    ]
