# Generated by Django 4.1.3 on 2023-04-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0009_vendedor_email_alter_propiedad_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
