# Generated by Django 4.1.3 on 2023-04-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0010_alter_vendedor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='vendedor',
            new_name='vendedor_id',
        ),
    ]
