# Generated by Django 4.1.3 on 2023-04-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0011_rename_vendedor_propiedad_vendedor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_inmobiliaria.vendedor')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_inmobiliaria.propiedad')),
            ],
        ),
    ]
