# Generated by Django 4.1.3 on 2023-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0013_alter_agenda_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
