# Generated by Django 4.1.3 on 2023-04-26 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0016_reserva_confirmada_reserva_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
