# Generated by Django 4.1.3 on 2023-04-26 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0017_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2023, 4, 26, 20, 44, 35, 237781, tzinfo=datetime.timezone.utc)),
        ),
    ]
