# Generated by Django 4.1.3 on 2023-04-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0018_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
