# Generated by Django 4.1.3 on 2023-04-26 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0020_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2023, 4, 26, 21, 29, 17, 144411, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(limit_choices_to={'disponible': True}, on_delete=django.db.models.deletion.CASCADE, to='sistema_inmobiliaria.propiedad'),
        ),
    ]
