# Generated by Django 4.2.3 on 2025-07-23 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0021_alter_reserva_fecha_inicio_alter_reserva_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='confirmada',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 18, 57, 7, 427088, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_inmobiliaria.propiedad'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del artículo', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=200, unique=True)),
                ('contenido', models.TextField(help_text='Contenido completo del artículo (HTML permitido)')),
                ('resumen', models.TextField(blank=True, help_text='Resumen corto para mostrar en listados', max_length=300)),
                ('autor', models.CharField(default='Admin', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen destacada del artículo', null=True, upload_to='blog/')),
                ('imagen_alt', models.CharField(blank=True, help_text='Texto alternativo para la imagen', max_length=200)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('tiempo_lectura', models.PositiveIntegerField(default=5, help_text='Tiempo estimado de lectura en minutos')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar como artículo destacado')),
                ('meta_descripcion', models.CharField(blank=True, help_text='Descripción para motores de búsqueda', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=200)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_inmobiliaria.categoria')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_publicacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_publicacion'], name='sistema_inm_estado_04b587_idx'), models.Index(fields=['categoria', 'estado'], name='sistema_inm_categor_52bfb0_idx'), models.Index(fields=['destacado', 'estado'], name='sistema_inm_destaca_af1ac3_idx')],
            },
        ),
    ]
