# Generated by Django 4.2.3 on 2025-07-23 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0022_categoria_remove_reserva_confirmada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 21, 18, 57, 485960, tzinfo=datetime.timezone.utc)),
        ),
    ]
