# Generated by Django 4.2.3 on 2025-07-23 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0023_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 21, 19, 6, 516232, tzinfo=datetime.timezone.utc)),
        ),
    ]
