# Generated by Django 4.2.3 on 2025-07-23 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0024_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono opcional', max_length=15)),
                ('asunto', models.CharField(help_text='Asunto de la consulta', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje o consulta')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('respondida', models.BooleanField(default=False, help_text='Marca si ya fue respondida')),
            ],
            options={
                'verbose_name': 'Consulta General',
                'verbose_name_plural': 'Consultas Generales',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='SuscriptorNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del suscriptor', max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre opcional', max_length=100)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Suscripción activa')),
                ('confirmado', models.BooleanField(default=False, help_text='Email confirmado')),
                ('token_confirmacion', models.CharField(blank=True, help_text='Token para confirmar email', max_length=100)),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(upload_to='propiedades/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 22, 32, 30, 165189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SolicitudVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del interesado', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=15)),
                ('fecha_preferida', models.DateField(help_text='Fecha preferida para la visita')),
                ('hora_preferida', models.TimeField(help_text='Hora preferida para la visita')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje adicional')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('respuesta_agente', models.TextField(blank=True, help_text='Respuesta del agente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_visita', to='sistema_inmobiliaria.propiedad')),
            ],
            options={
                'verbose_name': 'Solicitud de Visita',
                'verbose_name_plural': 'Solicitudes de Visita',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ContactoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del interesado', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono opcional', max_length=15)),
                ('mensaje', models.TextField(help_text='Consulta o mensaje')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('respondida', models.BooleanField(default=False, help_text='Marca si ya fue respondida')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='sistema_inmobiliaria.propiedad')),
            ],
            options={
                'verbose_name': 'Consulta de Propiedad',
                'verbose_name_plural': 'Consultas de Propiedades',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
