# Generated by Django 4.2.3 on 2025-07-24 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0026_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del consultante', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono opcional', max_length=15)),
                ('mensaje', models.TextField(help_text='Mensaje o consulta')),
                ('origen', models.CharField(choices=[('propiedad', 'Consulta desde Propiedad'), ('general', 'Consulta General'), ('contacto', 'Página de Contacto'), ('home', 'Página Principal'), ('newsletter', 'Newsletter')], help_text='Desde dónde se hizo la consulta', max_length=20)),
                ('tipo', models.CharField(choices=[('compra', 'Interés en Compra'), ('venta', 'Interés en Venta'), ('alquiler', 'Interés en Alquiler'), ('informacion', 'Solicitud de Información'), ('general', 'Consulta General'), ('otro', 'Otro')], default='general', help_text='Tipo de consulta', max_length=20)),
                ('asunto', models.CharField(blank=True, help_text='Asunto específico', max_length=200)),
                ('presupuesto', models.CharField(blank=True, help_text='Presupuesto estimado', max_length=50)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('respondida', models.BooleanField(default=False, help_text='Marca si ya fue respondida')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta del agente')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha de respuesta', null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas del equipo')),
                ('propiedad', models.ForeignKey(blank=True, help_text='Propiedad relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='sistema_inmobiliaria.propiedad')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='propiedad',
        ),
        migrations.DeleteModel(
            name='ContactoGeneral',
        ),
        migrations.RemoveField(
            model_name='contactopropiedad',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='propiedad',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='ContactoPropiedad',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['origen', 'fecha_consulta'], name='sistema_inm_origen_d23fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['respondida', 'prioridad'], name='sistema_inm_respond_a70039_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['propiedad', 'fecha_consulta'], name='sistema_inm_propied_3fa178_idx'),
        ),
    ]
