# Generated by Django 4.2.3 on 2025-07-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_inmobiliaria', '0027_consulta_remove_agenda_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del vendedor', null=True, upload_to='vendedores/'),
        ),
    ]
